services:
  platform:
    build:
      context: .
      dockerfile: platform/Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      PLATFORM_PORT: "7860"

  message-bot:
    build:
      context: .
      dockerfile: message-bot/Dockerfile
    ports:
      - "7861:7861"
    env_file:
      - .env
    environment:
      MESSAGE_BOT_PORT: "7861"
